### ISSUE TITLE
CircuitPython remount in boot.py makes drive readonly to PC.

### ISSUE THREAD

**Issue by freemansoft** [BrianPugh/belay#94]
I have this boot.py per the instructions and now the device is mounted read only to my pc.  I think it changes the drive from writable via circuitpython and read only to the computer.  You may wish to add notes on how to remove that `boot.py` from the repl so that people can code with files on the drive again.

- https://docs.circuitpython.org/en/latest/shared-bindings/storage/index.html
- https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage
- 

```
import storage

storage.remount("/")
```

**Comment by BrianPugh** [comment]
I'll add documentation to the circuitpython section with the commands you provided, as well as instructions how to delete the ``boot.py``

**Comment by freemansoft** [comment]
```
import os
os.listdir()
os.remove("boot.py")
```

**Comment by BrianPugh** [comment]
I added more documentation in #96. Closing this for now, if you have feedback please provide it in the PR. I'll be merging it after I update some other documentation sections on new features.
